fix(core): Fixes compatibility with Mopidy >= 4.0
Mopidy v4.0 has migrated to Pydantic instead of the previous self-made
(and more tolerant) schemas, and a track or album can't have an empty
string as a date.

Pydantic will fail with:

```
  File "/home/blacklight/git_tree/mopidy/venv/lib/python3.13/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Album
date
  String should match pattern '^\d{4}(-\d{2}-\d{2})?$' [type=string_pattern_mismatch, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/string_pattern_mismatch
```

This fixes the issue by falling back to `DateCreated` (which should
always be provided by the server), and just in case it falls back to
1970-01-01 if that isn't available either.